export const people = [
    {
      id: '1',
      name: 'Luke Skywalker',
      pincode: 248006,
      quantity: '77',
      type: 'Cotton',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'fair',
      Price: 'Rs. 12000',
      certificate_code: 'male',
    },
    
    {
      id: '2',
      name: 'C-3PO',
      pincode: 248006,
      quantity: '75',
      type: 'Nylon',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      color: 'gold',
      Price: 'Rs. 10000',
      certificate_code: 'n/a',
    },
    {
      id: '3',
      name: 'R2-D2',
      pincode: 248006,
      quantity: '32',
      type: 'Wool',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'white, blue',
      Price: 'Rs. 12300',
      certificate_code: 'n/a',
    },
    {
      id: '4',
      name: 'Darth Vader',
      pincode: 248006,
      quantity: '136',
      type: 'Silk',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'white',
      Price: 'Rs. 230000',
      certificate_code: 'male',
    },
    {
      id: '5',
      name: 'Leia Organa',
      pincode: 248006,
      quantity: '49',
      type: 'Mix fabrics',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'light',
      Price: 'Rs. 20000',
      certificate_code: 'female',
    },
    {
      id: '6',
      name: 'Owen Lars',
      pincode: 248006,
      quantity: '120',
      type: 'Cotton with 15% polysterene',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'light',
      Price: 'Rs. 3 lakhs',
      certificate_code: 'male',
    },
    {
      id: '7',
      name: 'Beru Whitesun Lars',
      pincode: 248006,
      quantity: '75',
      type: 'Polysterene fibres',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'light',
      Price: 'Rs. 20000',
      certificate_code: 'female',
    },
    {
      id: '8',
      name: 'R5-D4',
      pincode: 248006,
      quantity: '32',
      type: 'Cotton strips',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      
      color: 'white, red',
      Price: 'Rs. 50,000',
      certificate_code: 'n/a',
    },
    {
      id: '9',
      name: 'Biggs Darklighter',
      pincode: 248006,
      quantity: '84',
      type: 'Shredded wool fibres',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien felis, facilisis at sem sed, pulvinar vulputate arcu. Nunc consequat vehicula eros, vel scelerisque urna tincidunt eget. Praesent elementum lectus sed quam facilisis, vel pulvinar sapien faucibus. Pellentesque lobortis gravida est ac aliquet. Nullam sollicitudin interdum mauris, nec porta enim blandit eu. Praesent eget lacus tortor. Integer suscipit nisi quis velit tincidunt, auctor condimentum quam pretium. Fusce malesuada consequat ligula, sed sagittis leo pharetra nec. Integer nec tempor odio. Aenean sagittis tortor id felis suscipit laoreet non at metus.",
      Price: 'Rs. 40 lakhs',
      certificate_code: 'male',
    },
   
  ]
  